server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bookings
          uri: lb://bookings
          predicates:
            - Path=/api/v2/poli/booking/**
        - id: movies
          uri: lb://movies
          predicates:
            - Path=/api/v2/poli/movie/**
        - id: showtimes
          uri: lb://showtimes
          predicates:
            - Path=/api/v2/poli/showtime/**
        - id: users
          uri: lb://users
          predicates:
            - Path=/api/v2/poli/user/**