server:
  servlet:
    context-path: /api/v2/poli
  port: 9081
spring:
  application:
    name: movies
  profiles:
    active: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

